const stateData = () => {
  const stateOptions = [
    {
      label: "آذربایجان شرقی",
      value: "آذربایجان شرقی",
      cities: [
        { label: "اسكو", value: "اسكو" },
        { label: "اهر", value: "اهر" },
        { label: "ایلخچی", value: "ایلخچی" },
        { label: "باسمنج", value: "باسمنج" },
        { label: "بستان آباد", value: "بستان آباد" },
        { label: "بناب", value: "بناب" },
        { label: "تبريز", value: "تبريز" },
        { label: "تسوج", value: "تسوج" },
        { label: "جلفا", value: "جلفا" },
        { label: "خسروشهر", value: "خسروشهر" },
        { label: "سراب", value: "سراب" },
        { label: "سهند", value: "سهند" },
        { label: "شبستر", value: "شبستر" },
        { label: "صوفیان", value: "صوفیان" },
        { label: "مراغه", value: "مراغه" },
        { label: "مرند", value: "مرند" },
        { label: "ملكان", value: "ملكان" },
        { label: "ممقان", value: "ممقان" },
        { label: "ميانه", value: "ميانه" },
        { label: "هاديشهر", value: "هاديشهر" },
        { label: "هريس", value: "هريس" },
        { label: "هشترود", value: "هشترود" },
        { label: "ورزقان", value: "ورزقان" },
      ],
    },
    {
      label: "آذربایجان غربی",
      value: "آذربایجان غربی",
      cities: [
        { label: "اروميه", value: "اروميه" },
        { label: "اشنويه", value: "اشنويه" },
        { label: "بوكان", value: "بوكان" },
        { label: "تكاب", value: "تكاب" },
        { label: "خوي", value: "خوي" },
        { label: "سر دشت", value: "سر دشت" },
        { label: "سلماس", value: "سلماس" },
        { label: "شاهين دژ", value: "شاهين دژ" },
        { label: "ماكو", value: "ماكو" },
        { label: "مهاباد", value: "مهاباد" },
        { label: "مياندوآب", value: "مياندوآب" },
        { label: "نقده", value: "نقده" },
        { label: "پلدشت", value: "پلدشت" },
        { label: "پيرانشهر", value: "پيرانشهر" },
        { label: "چالدران", value: "چالدران" },
      ],
    },
    {
      label: "اردبیل",
      value: "اردبیل",
      cities: [
        { label: "اردبيل", value: "اردبيل" },
        { label: "خلخال", value: "خلخال" },
        { label: "مشگين شهر", value: "مشگين شهر" },
        { label: "نمين", value: "نمين" },
        { label: "نير", value: "نير" },
        { label: "پارس آباد", value: "پارس آباد" },
        { label: "گرمي", value: "گرمي" },
      ],
    },
    {
      label: "اصفهان",
      value: "اصفهان",
      cities: [
        { label: "آران و بيدگل", value: "آران و بيدگل" },
        { label: "اردستان", value: "اردستان" },
        { label: "اصفهان", value: "اصفهان" },
        { label: "باغ بهادران", value: "باغ بهادران" },
        { label: "تودشک", value: "تودشک" },
        { label: "تيران", value: "تيران" },
        { label: "حاجي آباد", value: "حاجي آباد" },
        { label: "خميني شهر", value: "خميني شهر" },
        { label: "خوانسار", value: "خوانسار" },
        { label: "درچه", value: "درچه" },
        { label: "دهاقان", value: "دهاقان" },
        { label: "زرين شهر", value: "زرين شهر" },
        { label: "سميرم", value: "سميرم" },
        { label: "شهرضا", value: "شهرضا" },
        { label: "عسگران", value: "عسگران" },
        { label: "علويجه", value: "علويجه" },
        { label: "فلاورجان", value: "فلاورجان" },
        { label: "كاشان", value: "كاشان" },
        { label: "مباركه", value: "مباركه" },
        { label: "نجف آباد", value: "نجف آباد" },
        { label: "نطنز", value: "نطنز" },
        { label: "ورزنه", value: "ورزنه" },
        { label: "کوهپایه", value: "کوهپایه" },
        { label: "گلپايگان", value: "گلپايگان" },
      ],
    },
    {
      label: "ایلام",
      value: "ایلام",
      cities: [
        { label: "آبدانان", value: "آبدانان" },
        { label: "ايلام", value: "ايلام" },
        { label: "ايوان", value: "ايوان" },
        { label: "دره شهر", value: "دره شهر" },
        { label: "دهلران", value: "دهلران" },
        { label: "سرابله", value: "سرابله" },
        { label: "مهران", value: "مهران" },
      ],
    },
    {
      label: "بوشهر",
      value: "بوشهر",
      cities: [
        { label: "اهرم", value: "اهرم" },
        { label: "برازجان", value: "برازجان" },
        { label: "بوشهر", value: "بوشهر" },
        { label: "جم", value: "جم" },
        { label: "خورموج", value: "خورموج" },
        { label: "دير", value: "دير" },
        { label: "عسلویه", value: "عسلویه" },
        { label: "كنگان", value: "كنگان" },
        { label: "کاکی", value: "کاکی" },
        { label: "گناوه", value: "گناوه" },
      ],
    },
    {
      label: "تهران",
      value: "تهران",
      cities: [
        { label: "اسلامشهر", value: "اسلامشهر" },
        { label: "باقرشهر", value: "باقرشهر" },
        { label: "بومهن", value: "بومهن" },
        { label: "تجريش", value: "تجريش" },
        { label: "تهران", value: "تهران" },
        { label: "دماوند", value: "دماوند" },
        { label: "رباط كريم", value: "رباط كريم" },
        { label: "رودهن", value: "رودهن" },
        { label: "ري", value: "ري" },
        { label: "شريف آباد", value: "شريف آباد" },
        { label: "شهريار", value: "شهريار" },
        { label: "فشم", value: "فشم" },
        { label: "فيروزكوه", value: "فيروزكوه" },
        { label: "قدس", value: "قدس" },
        { label: "قرچك", value: "قرچك" },
        { label: "كهريزك", value: "كهريزك" },
        { label: "لواسان", value: "لواسان" },
        { label: "ملارد", value: "ملارد" },
        { label: "ورامين", value: "ورامين" },
        { label: "پاكدشت", value: "پاكدشت" },
        { label: "چهاردانگه", value: "چهاردانگه" },
      ],
    },
    {
      label: "چهارمحال و بختیاری",
      value: "چهارمحال و بختیاری",
      cities: [
        { label: "اردل", value: "اردل" },
        { label: "بروجن", value: "بروجن" },
        { label: "جونقان", value: "جونقان" },
        { label: "سامان", value: "سامان" },
        { label: "شهركرد", value: "شهركرد" },
        { label: "فارسان", value: "فارسان" },
        { label: "لردگان", value: "لردگان" },
        { label: "چلگرد", value: "چلگرد" },
        { label: "فرادبنه", value: "فرادبنه" },
        { label: "سودجان", value: "سودجان" },
        { label: "نافچ", value: "نافچ" },
      ],
    },
    {
      label: "خراسان جنوبی",
      value: "خراسان جنوبی",
      cities: [
        { label: "بيرجند", value: "بيرجند" },
        { label: "خضری", value: "خضری" },
        { label: "سرايان", value: "سرايان" },
        { label: "سر بیشه", value: "سر بیشه" },
        { label: "فردوس", value: "فردوس" },
        { label: "قائن", value: "قائن" },
        { label: "مهرستان", value: "مهرستان" },
        { label: "نهبندان", value: "نهبندان" },
        { label: "طبس", value: "طبس" },
      ],
    },
    {
      label: "خراسان رضوی",
      value: "خراسان رضوی",
      cities: [
        { label: "تايباد", value: "تايباد" },
        { label: "تربت جام", value: "تربت جام" },
        { label: "تربت حيدريه", value: "تربت حيدريه" },
        { label: "چناران", value: "چناران" },
        { label: "خواف", value: "خواف" },
        { label: "درگز", value: "درگز" },
        { label: "سبزوار", value: "سبزوار" },
        { label: "سرخس", value: "سرخس" },
        { label: "فريمان", value: "فريمان" },
        { label: "قوچان", value: "قوچان" },
        { label: "كاشمر", value: "كاشمر" },
        { label: "گناباد", value: "گناباد" },
        { label: "مشهد", value: "مشهد" },
        { label: "نيشابور", value: "نيشابور" },
      ],
    },
    {
      label: "خراسان شمالی",
      value: "خراسان شمالی",
      cities: [
        { label: "اسفراين", value: "اسفراين" },
        { label: "بجنورد", value: "بجنورد" },
        { label: "جاجرم", value: "جاجرم" },
        { label: "شيروان", value: "شيروان" },
        { label: "فاروج", value: "فاروج" },
        { label: "گرمه", value: "گرمه" },
      ],
    },
    {
      label: "خوزستان",
      value: "خوزستان",
      cities: [
        { label: "آبادان", value: "آبادان" },
        { label: "انديمشك", value: "انديمشك" },
        { label: "اهواز", value: "اهواز" },
        { label: "ايرانشهر", value: "ايرانشهر" },
        { label: "ايذه", value: "ايذه" },
        { label: "بندر ماهشهر", value: "بندر ماهشهر" },
        { label: "بندر امام خميني", value: "بندر امام خميني" },
        { label: "باغ ملك", value: "باغ ملك" },
        { label: "بهبهان", value: "بهبهان" },
        { label: "خرمشهر", value: "خرمشهر" },
        { label: "دزفول", value: "دزفول" },
        { label: "رامهرمز", value: "رامهرمز" },
        { label: "شادگان", value: "شادگان" },
        { label: "شوش", value: "شوش" },
        { label: "شوشتر", value: "شوشتر" },
        { label: "لالی", value: "لالی" },
        { label: "مسجد سليمان", value: "مسجد سليمان" },
        { label: "هندیجان", value: "هندیجان" },
      ],
    },
    {
      label: "زنجان",
      value: "زنجان",
      cities: [
        { label: "ابهر", value: "ابهر" },
        { label: "خرمدره", value: "خرمدره" },
        { label: "زنجان", value: "زنجان" },
        { label: "قيدار", value: "قيدار" },
        { label: "ماهنشان", value: "ماهنشان" },
        { label: "همايون", value: "همايون" },
        { label: "آب بر", value: "آب بر" },
      ],
    },
    {
      label: "سمنان",
      value: "سمنان",
      cities: [
        { label: "ايوانكي", value: "ايوانكي" },
        { label: "بسطام", value: "بسطام" },
        { label: "دامغان", value: "دامغان" },
        { label: "سرخه", value: "سرخه" },
        { label: "شاهرود", value: "شاهرود" },
        { label: "سمنان", value: "سمنان" },
        { label: "شهميرزاد", value: "شهميرزاد" },
        { label: "گرمسار", value: "گرمسار" },
      ],
    },
    {
      label: "سیستان و بلوچستان",
      value: "سیستان و بلوچستان",
      cities: [
        { label: "ايرانشهر", value: "ايرانشهر" },
        { label: "چابهار", value: "چابهار" },
        { label: "خاش", value: "خاش" },
        { label: "زابل", value: "زابل" },
        { label: "زاهدان", value: "زاهدان" },
        { label: "سراوان", value: "سراوان" },
        { label: "سرباز", value: "سرباز" },
        { label: "كنارك", value: "كنارك" },
      ],
    },
    {
      label: "فارس",
      value: "فارس",
      cities: [
        { label: "آباده", value: "آباده" },
        { label: "ارسنجان", value: "ارسنجان" },
        { label: "استهبان", value: "استهبان" },
        { label: "اقليد", value: "اقليد" },
        { label: "اوز", value: "اوز" },
        { label: "ايزدخواست", value: "ايزدخواست" },
        { label: "باب انار", value: "باب انار" },
        { label: "بالاده", value: "بالاده" },
        { label: "بنارویه", value: "بنارویه" },
        { label: "بوانات", value: "بوانات" },
        { label: "بيرم", value: "بيرم" },
        { label: "جهرم", value: "جهرم" },
        { label: "حاجي آباد", value: "حاجي آباد" },
        { label: "خاوران", value: "خاوران" },
        { label: "خنج", value: "خنج" },
        { label: "داراب", value: "داراب" },
        { label: "زرقان", value: "زرقان" },
        { label: "سروستان", value: "سروستان" },
        { label: "سعادت شهر", value: "سعادت شهر" },
        { label: "سوريان", value: "سوريان" },
        { label: "ششده", value: "ششده" },
        { label: "شيراز", value: "شيراز" },
        { label: "صغاد", value: "صغاد" },
        { label: "صفاشهر", value: "صفاشهر" },
        { label: "فراشبند", value: "فراشبند" },
        { label: "فسا", value: "فسا" },
        { label: "فيروزآباد", value: "فيروزآباد" },
        { label: "قير", value: "قير" },
        { label: "كازرون", value: "كازرون" },
        { label: "كنارتخته", value: "كنارتخته" },
        { label: "گراش", value: "گراش" },
        { label: "لار", value: "لار" },
        { label: "لامرد", value: "لامرد" },
        { label: "مرودشت", value: "مرودشت" },
        { label: "مهر", value: "مهر" },
        { label: "ميمند", value: "ميمند" },
        { label: "وراوی", value: "وراوی" },
      ],
    },
    {
      label: "قزوین",
      value: "قزوین",
      cities: [
        { label: "آبيك", value: "آبيك" },
        { label: "آبگرم", value: "آبگرم" },
        { label: "آوج", value: "آوج" },
        { label: "بوئين زهرا", value: "بوئين زهرا" },
        { label: "تاكستان", value: "تاكستان" },
        { label: "قزوين", value: "قزوين" },
        { label: "محمود آباد نمونه", value: "محمود آباد نمونه" },
        { label: "رازمیان", value: "رازمیان" },
        { label: "سیردان", value: "سیردان" },
      ],
    },
    {
      label: "قم",
      value: "قم",
      cities: [{ label: "قم", value: "قم" }],
    },
    {
      label: "کردستان",
      value: "کردستان",
      cities: [
        { label: "بانه", value: "بانه" },
        { label: "بيجار", value: "بيجار" },
        { label: "دهگلان", value: "دهگلان" },
        { label: "ديواندره", value: "ديواندره" },
        { label: "سقز", value: "سقز" },
        { label: "سنندج", value: "سنندج" },
        { label: "قروه", value: "قروه" },
        { label: "مريوان", value: "مريوان" },
        { label: "كامياران", value: "كامياران" },
      ],
    },
    {
      label: "کرمان",
      value: "کرمان",
      cities: [
        { label: "بافت", value: "بافت" },
        { label: "بردسير", value: "بردسير" },
        { label: "بم", value: "بم" },
        { label: "جيرفت", value: "جيرفت" },
        { label: "راور", value: "راور" },
        { label: "رفسنجان", value: "رفسنجان" },
        { label: "زرند", value: "زرند" },
        { label: "سيرجان", value: "سيرجان" },
        { label: "كرمان", value: "كرمان" },
        { label: "كهنوج", value: "كهنوج" },
        { label: "لاله زار", value: "لاله زار" },
        { label: "ماهان", value: "ماهان" },
        { label: "منوجان", value: "منوجان" },
        { label: "رودبار", value: "رودبار" },
      ],
    },
    {
      label: "کرمانشاه",
      value: "کرمانشاه",
      cities: [
        { label: "اسلام آباد غرب", value: "اسلام آباد غرب" },
        { label: "باينگان", value: "باينگان" },
        { label: "پاوه", value: "پاوه" },
        { label: "تازه آباد", value: "تازه آباد" },
        { label: "جوانرود", value: "جوانرود" },
        { label: "سنقر", value: "سنقر" },
        { label: "صحنه", value: "صحنه" },
        { label: "قصر شيرين", value: "قصر شيرين" },
        { label: "كرمانشاه", value: "كرمانشاه" },
        { label: "كنگاور", value: "كنگاور" },
        { label: "گيلانغرب", value: "گيلانغرب" },
        { label: "هرسين", value: "هرسين" },
      ],
    },
    {
      label: "کهگیلویه و بویراحمد",
      value: "کهگیلویه و بویراحمد",
      cities: [
        { label: "دهدشت", value: "دهدشت" },
        { label: "دوگنبدان", value: "دوگنبدان" },
        { label: "سي سخت", value: "سي سخت" },
        { label: "گچساران", value: "گچساران" },
        { label: "ياسوج", value: "ياسوج" },
      ],
    },
    {
      label: "گلستان",
      value: "گلستان",
      cities: [
        { label: "آزاد شهر", value: "آزاد شهر" },
        { label: "آق قلا", value: "آق قلا" },
        { label: "بندر گز", value: "بندر گز" },
        { label: "راميان", value: "راميان" },
        { label: "علي آباد كتول", value: "علي آباد كتول" },
        { label: "كردكوي", value: "كردكوي" },
        { label: "كلاله", value: "كلاله" },
        { label: "گنبد كاووس", value: "گنبد كاووس" },
        { label: "گرگان", value: "گرگان" },
        { label: "مراوه تپه", value: "مراوه تپه" },
        { label: "مينو دشت", value: "مينو دشت" },
      ],
    },
    {
      label: "گیلان",
      value: "گیلان",
      cities: [
        { label: "آستارا", value: "آستارا" },
        { label: "املش", value: "املش" },
        { label: "بندرانزلي", value: "بندرانزلي" },
        { label: "رشت", value: "رشت" },
        { label: "رودبار", value: "رودبار" },
        { label: "رودسر", value: "رودسر" },
        { label: "سياهكل", value: "سياهكل" },
        { label: "شفت", value: "شفت" },
        { label: "صومعه سرا", value: "صومعه سرا" },
        { label: "فومن", value: "فومن" },
        { label: "لاهیجان", value: "لاهیجان" },
        { label: "لنگرود", value: "لنگرود" },
        { label: "ماسال", value: "ماسال" },
      ],
    },
    {
      label: "لرستان",
      value: "لرستان",
      cities: [
        { label: "ازنا", value: "ازنا" },
        { label: "الشتر", value: "الشتر" },
        { label: "اليگودرز", value: "اليگودرز" },
        { label: "بروجرد", value: "بروجرد" },
        { label: "پلدختر", value: "پلدختر" },
        { label: "خرم آباد", value: "خرم آباد" },
        { label: "دورود", value: "دورود" },
        { label: "سپيددشت", value: "سپيددشت" },
        { label: "نور آباد", value: "نور آباد" },
        { label: "كوهدشت", value: "كوهدشت" },
      ],
    },
    {
      label: "مازندران",
      value: "مازندران",
      cities: [
        { label: "آمل", value: "آمل" },
        { label: "بابل", value: "بابل" },
        { label: "بابلسر", value: "بابلسر" },
        { label: "بهشهر", value: "بهشهر" },
        { label: "تنكابن", value: "تنكابن" },
        { label: "جویبار", value: "جویبار" },
        { label: "چالوس", value: "چالوس" },
        { label: "رامسر", value: "رامسر" },
        { label: "ساري", value: "ساري" },
        { label: "سواد كوه", value: "سواد كوه" },
        { label: "فريدون كنار", value: "فريدون كنار" },
        { label: "قائم شهر", value: "قائم شهر" },
        { label: "گلوگاه", value: "گلوگاه" },
        { label: "محمود آباد", value: "محمود آباد" },
        { label: "مرزن آباد", value: "مرزن آباد" },
        { label: "نور", value: "نور" },
        { label: "نوشهر", value: "نوشهر" },
      ],
    },
    {
      label: "مرکزی",
      value: "مرکزی",
      cities: [
        { label: "آشتيان", value: "آشتيان" },
        { label: "اراك", value: "اراك" },
        { label: "تفرش", value: "تفرش" },
        { label: "خمين", value: "خمين" },
        { label: "خنداب", value: "خنداب" },
        { label: "دليجان", value: "دليجان" },
        { label: "زرنديه", value: "زرنديه" },
        { label: "ساوه", value: "ساوه" },
        { label: "شازند", value: "شازند" },
        { label: "محلات", value: "محلات" },
      ],
    },
    {
      label: "هرمزگان",
      value: "هرمزگان",
      cities: [
        { label: "بستك", value: "بستك" },
        { label: "بندر جاسك", value: "بندر جاسك" },
        { label: "بندر لنگه", value: "بندر لنگه" },
        { label: "بندرعباس", value: "بندرعباس" },
        { label: "حاجي آباد", value: "حاجي آباد" },
        { label: "دهبارز", value: "دهبارز" },
        { label: "قشم", value: "قشم" },
        { label: "كيش", value: "كيش" },
        { label: "ميناب", value: "ميناب" },
      ],
    },
    {
      label: "همدان",
      value: "همدان",
      cities: [
        { label: "بهار", value: "بهار" },
        { label: "تويسركان", value: "تويسركان" },
        { label: "رزن", value: "رزن" },
        { label: "كبودر اهنگ", value: "كبودر اهنگ" },
        { label: "ملاير", value: "ملاير" },
        { label: "نهاوند", value: "نهاوند" },
        { label: "همدان", value: "همدان" },
      ],
    },
    {
      label: "یزد",
      value: "یزد",
      cities: [
        { label: "ابركوه", value: "ابركوه" },
        { label: "اردكان", value: "اردكان" },
        { label: "بافق", value: "بافق" },
        { label: "تفت", value: "تفت" },
        { label: "مهريز", value: "مهريز" },
        { label: "ميبد", value: "ميبد" },
        { label: "هرات", value: "هرات" },
        { label: "يزد", value: "يزد" },
      ],
    },
  ];

  return stateOptions;
};

export default stateData;
